language: julia
os:
  - linux
  - osx
  - windows

julia:
  - nightly
  - 1.3.1
  - 1.4.0
  - 1.4.1

codecov: true

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.add("Documenter"); Pkg.add("CSV");
                                  Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Network_qse")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
